version: '2'
services:
    jhproj-app:
        image: jhproj
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhproj-mysql:3306/jhproj?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhproj-mysql:
        extends:
            file: mysql.yml
            service: jhproj-mysql
